PREFIX my: <http://www.semanticweb.org/jgh88/ontologies/2023/8/untitled-ontology-3#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?profile ?behavior ?illness ?susceptibility WHERE {
VALUES ?profile { my:PWD_1_Paul my:PWD_2 my:PWD_3_John my:PWD_4 my:PWD_5 }
?profile rdf:type my:Person ; my:behaviors ?behavior .
?behavior rdf:type my:Harmful_Behavior ; my:Results ?illness .
OPTIONAL { ?behavior my:susceptibilities ?susceptibility . ?susceptibility my:susceptibilityTo ?illness . }
}
ORDER BY ?profile ?behavior ?illness ?susceptibility
